// <auto-generated />
using System;
using DrivingSchoolApi.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DrivingSchoolApi.Infrastructure.Database.Migrations
{
    [DbContext(typeof(DrivingSchoolDbContext))]
    [Migration("20260302135309_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DrivingSchoolApi.Domain.Entities.DrivingLesson", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InstructorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InstructorId");

                    b.HasIndex("SchoolId");

                    b.HasIndex("StudentId");

                    b.ToTable("DrivingLessons");
                });

            modelBuilder.Entity("DrivingSchoolApi.Domain.Entities.DrivingSchool", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("DrivingSchoolName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WebAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DrivingSchools");
                });

            modelBuilder.Entity("DrivingSchoolApi.Domain.Entities.Instructor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.ToTable("Instructors");
                });

            modelBuilder.Entity("DrivingSchoolApi.Domain.Entities.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("DrivingSchoolApi.Domain.Entities.TheoryLesson", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InstructorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LessonDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InstructorId");

                    b.HasIndex("SchoolId");

                    b.ToTable("TheoryLessons");
                });

            modelBuilder.Entity("DrivingSchoolApi.Domain.Entities.DrivingLesson", b =>
                {
                    b.HasOne("DrivingSchoolApi.Domain.Entities.Instructor", null)
                        .WithMany()
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DrivingSchoolApi.Domain.Entities.DrivingSchool", null)
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DrivingSchoolApi.Domain.Entities.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("DrivingSchoolApi.Domain.ValueObjects.Money", "Price", b1 =>
                        {
                            b1.Property<Guid>("DrivingLessonId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("DrivingLessonId");

                            b1.ToTable("DrivingLessons");

                            b1.WithOwner()
                                .HasForeignKey("DrivingLessonId");
                        });

                    b.OwnsOne("DrivingSchoolApi.Domain.ValueObjects.DrivingRoute", "Route", b1 =>
                        {
                            b1.Property<Guid>("DrivingLessonId")
                                .HasColumnType("uuid");

                            b1.HasKey("DrivingLessonId");

                            b1.ToTable("DrivingLessons");

                            b1.WithOwner()
                                .HasForeignKey("DrivingLessonId");

                            b1.OwnsOne("DrivingSchoolApi.Domain.ValueObjects.DateTimeRange", "DateTimeRange", b2 =>
                                {
                                    b2.Property<Guid>("DrivingRouteDrivingLessonId")
                                        .HasColumnType("uuid");

                                    b2.Property<DateTime>("EndDateTime")
                                        .HasColumnType("timestamp with time zone");

                                    b2.Property<DateTime>("StartDateTime")
                                        .HasColumnType("timestamp with time zone");

                                    b2.HasKey("DrivingRouteDrivingLessonId");

                                    b2.ToTable("DrivingLessons");

                                    b2.WithOwner()
                                        .HasForeignKey("DrivingRouteDrivingLessonId");
                                });

                            b1.OwnsMany("DrivingSchoolApi.Domain.ValueObjects.CoordinatePoint", "RouteCoordinates", b2 =>
                                {
                                    b2.Property<Guid>("RouteId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Order")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Order"));

                                    b2.Property<float>("Latitude")
                                        .HasColumnType("real");

                                    b2.Property<float>("Longitude")
                                        .HasColumnType("real");

                                    b2.HasKey("RouteId", "Order");

                                    b2.ToTable("CoordinatePoint");

                                    b2.WithOwner()
                                        .HasForeignKey("RouteId");
                                });

                            b1.Navigation("DateTimeRange")
                                .IsRequired();

                            b1.Navigation("RouteCoordinates");
                        });

                    b.Navigation("Price")
                        .IsRequired();

                    b.Navigation("Route")
                        .IsRequired();
                });

            modelBuilder.Entity("DrivingSchoolApi.Domain.Entities.DrivingSchool", b =>
                {
                    b.OwnsOne("DrivingSchoolApi.Domain.ValueObjects.Address", "SchoolAddress", b1 =>
                        {
                            b1.Property<Guid>("DrivingSchoolId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AddressLine")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Region")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("DrivingSchoolId");

                            b1.ToTable("DrivingSchools");

                            b1.WithOwner()
                                .HasForeignKey("DrivingSchoolId");
                        });

                    b.Navigation("SchoolAddress")
                        .IsRequired();
                });

            modelBuilder.Entity("DrivingSchoolApi.Domain.Entities.Instructor", b =>
                {
                    b.HasOne("DrivingSchoolApi.Domain.Entities.DrivingSchool", null)
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("DrivingSchoolApi.Domain.ValueObjects.Name", "InstructorName", b1 =>
                        {
                            b1.Property<Guid>("InstructorId")
                                .HasColumnType("uuid");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("InstructorId");

                            b1.ToTable("Instructors");

                            b1.WithOwner()
                                .HasForeignKey("InstructorId");
                        });

                    b.Navigation("InstructorName")
                        .IsRequired();
                });

            modelBuilder.Entity("DrivingSchoolApi.Domain.Entities.Student", b =>
                {
                    b.HasOne("DrivingSchoolApi.Domain.Entities.DrivingSchool", null)
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("DrivingSchoolApi.Domain.ValueObjects.Name", "StudentName", b1 =>
                        {
                            b1.Property<Guid>("StudentId")
                                .HasColumnType("uuid");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("StudentId");

                            b1.ToTable("Students");

                            b1.WithOwner()
                                .HasForeignKey("StudentId");
                        });

                    b.Navigation("StudentName")
                        .IsRequired();
                });

            modelBuilder.Entity("DrivingSchoolApi.Domain.Entities.TheoryLesson", b =>
                {
                    b.HasOne("DrivingSchoolApi.Domain.Entities.Instructor", null)
                        .WithMany()
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DrivingSchoolApi.Domain.Entities.DrivingSchool", null)
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("DrivingSchoolApi.Domain.ValueObjects.Money", "Price", b1 =>
                        {
                            b1.Property<Guid>("TheoryLessonId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("TheoryLessonId");

                            b1.ToTable("TheoryLessons");

                            b1.WithOwner()
                                .HasForeignKey("TheoryLessonId");
                        });

                    b.OwnsMany("DrivingSchoolApi.Domain.Keys.StudentKey", "StudentIds", b1 =>
                        {
                            b1.Property<Guid>("TheoryLessonId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("StudentId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uuid");

                            b1.HasKey("TheoryLessonId", "StudentId");

                            b1.HasIndex("StudentId");

                            b1.ToTable("StudentTheoryLesson", (string)null);

                            b1.HasOne("DrivingSchoolApi.Domain.Entities.Student", null)
                                .WithMany()
                                .HasForeignKey("StudentId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("TheoryLessonId");
                        });

                    b.Navigation("Price")
                        .IsRequired();

                    b.Navigation("StudentIds");
                });
#pragma warning restore 612, 618
        }
    }
}
