// <auto-generated />
using System;
using DrivingSchoolApi.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DrivingSchoolApi.Infrastructure.Database.Migrations
{
    [DbContext(typeof(DrivingSchoolDbContext))]
    partial class DrivingSchoolDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DrivingSchoolApi.Domain.Entities.Admin", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EmailAddress")
                        .IsUnique();

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("DrivingSchoolApi.Domain.Entities.DrivingLesson", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InstructorId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("InstructorSignature")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("StudentSignature")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("InstructorId");

                    b.HasIndex("SchoolId");

                    b.HasIndex("StudentId");

                    b.ToTable("DrivingLessons");
                });

            modelBuilder.Entity("DrivingSchoolApi.Domain.Entities.DrivingSchool", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("DrivingSchoolName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WebAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DrivingSchools");
                });

            modelBuilder.Entity("DrivingSchoolApi.Domain.Entities.Instructor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EmailAddress")
                        .IsUnique();

                    b.HasIndex("SchoolId");

                    b.ToTable("Instructors");
                });

            modelBuilder.Entity("DrivingSchoolApi.Domain.Entities.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EmailAddress")
                        .IsUnique();

                    b.HasIndex("SchoolId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("DrivingSchoolApi.Domain.Entities.TheoryLesson", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InstructorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LessonDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InstructorId");

                    b.HasIndex("SchoolId");

                    b.ToTable("TheoryLessons");
                });

            modelBuilder.Entity("DrivingSchoolApi.Domain.Entities.DrivingLesson", b =>
                {
                    b.HasOne("DrivingSchoolApi.Domain.Entities.Instructor", null)
                        .WithMany()
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DrivingSchoolApi.Domain.Entities.DrivingSchool", null)
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DrivingSchoolApi.Domain.Entities.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("DrivingSchoolApi.Domain.ValueObjects.Money", "Price", b1 =>
                        {
                            b1.Property<Guid>("DrivingLessonId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("DrivingLessonId");

                            b1.ToTable("DrivingLessons");

                            b1.WithOwner()
                                .HasForeignKey("DrivingLessonId");
                        });

                    b.OwnsOne("DrivingSchoolApi.Domain.ValueObjects.DrivingRoute", "Route", b1 =>
                        {
                            b1.Property<Guid>("DrivingLessonId")
                                .HasColumnType("uuid");

                            b1.HasKey("DrivingLessonId");

                            b1.ToTable("DrivingLessons");

                            b1.WithOwner()
                                .HasForeignKey("DrivingLessonId");

                            b1.OwnsOne("DrivingSchoolApi.Domain.ValueObjects.DateTimeRange", "DateTimeRange", b2 =>
                                {
                                    b2.Property<Guid>("DrivingRouteDrivingLessonId")
                                        .HasColumnType("uuid");

                                    b2.Property<DateTime>("EndDateTime")
                                        .HasColumnType("timestamp with time zone");

                                    b2.Property<DateTime>("StartDateTime")
                                        .HasColumnType("timestamp with time zone");

                                    b2.HasKey("DrivingRouteDrivingLessonId");

                                    b2.ToTable("DrivingLessons");

                                    b2.WithOwner()
                                        .HasForeignKey("DrivingRouteDrivingLessonId");
                                });

                            b1.OwnsMany("DrivingSchoolApi.Domain.ValueObjects.CoordinatePoint", "RouteCoordinates", b2 =>
                                {
                                    b2.Property<Guid>("RouteId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Order")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Order"));

                                    b2.Property<float>("Latitude")
                                        .HasColumnType("real");

                                    b2.Property<float>("Longitude")
                                        .HasColumnType("real");

                                    b2.HasKey("RouteId", "Order");

                                    b2.ToTable("CoordinatePoint");

                                    b2.WithOwner()
                                        .HasForeignKey("RouteId");
                                });

                            b1.Navigation("DateTimeRange")
                                .IsRequired();

                            b1.Navigation("RouteCoordinates");
                        });

                    b.Navigation("Price")
                        .IsRequired();

                    b.Navigation("Route")
                        .IsRequired();
                });

            modelBuilder.Entity("DrivingSchoolApi.Domain.Entities.DrivingSchool", b =>
                {
                    b.OwnsMany("DrivingSchoolApi.Domain.Entities.StudentInvite", "StudentInvites", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("DrivingSchoolId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("ExpirationDateTime")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("Id");

                            b1.HasIndex("DrivingSchoolId");

                            b1.ToTable("StudentInvites");

                            b1.WithOwner()
                                .HasForeignKey("DrivingSchoolId");
                        });

                    b.OwnsOne("DrivingSchoolApi.Domain.ValueObjects.StreetAddress", "StreetAddress", b1 =>
                        {
                            b1.Property<Guid>("DrivingSchoolId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AddressLine")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Region")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("DrivingSchoolId");

                            b1.ToTable("DrivingSchools");

                            b1.WithOwner()
                                .HasForeignKey("DrivingSchoolId");
                        });

                    b.OwnsMany("DrivingSchoolApi.Domain.ValueObjects.Package", "Packages", b1 =>
                        {
                            b1.Property<Guid>("SchoolId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Title")
                                .HasColumnType("text");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("SchoolId", "Title");

                            b1.ToTable("SchoolPackage", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("SchoolId");

                            b1.OwnsOne("DrivingSchoolApi.Domain.ValueObjects.Money", "Price", b2 =>
                                {
                                    b2.Property<Guid>("PackageSchoolId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("PackageTitle")
                                        .HasColumnType("text");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("numeric");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("PackageSchoolId", "PackageTitle");

                                    b2.ToTable("SchoolPackage");

                                    b2.WithOwner()
                                        .HasForeignKey("PackageSchoolId", "PackageTitle");
                                });

                            b1.Navigation("Price")
                                .IsRequired();
                        });

                    b.Navigation("Packages");

                    b.Navigation("StreetAddress")
                        .IsRequired();

                    b.Navigation("StudentInvites");
                });

            modelBuilder.Entity("DrivingSchoolApi.Domain.Entities.Instructor", b =>
                {
                    b.HasOne("DrivingSchoolApi.Domain.Entities.DrivingSchool", null)
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("DrivingSchoolApi.Domain.Entities.InstructorCalender", "Calender", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.ToTable("Instructors");

                            b1.WithOwner()
                                .HasForeignKey("Id");

                            b1.OwnsMany("DrivingSchoolApi.Domain.ValueObjects.TimeSlot", "TimeSlots", b2 =>
                                {
                                    b2.Property<Guid>("InstructorId")
                                        .HasColumnType("uuid");

                                    b2.Property<DateTime>("StartDateTime")
                                        .HasColumnType("timestamp with time zone");

                                    b2.Property<DateTime>("EndDateTime")
                                        .HasColumnType("timestamp with time zone");

                                    b2.Property<string>("Description")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("InstructorId", "StartDateTime", "EndDateTime");

                                    b2.ToTable("InstructorTimeSlots", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("InstructorId");
                                });

                            b1.Navigation("TimeSlots");
                        });

                    b.OwnsOne("DrivingSchoolApi.Domain.ValueObjects.Name", "InstructorName", b1 =>
                        {
                            b1.Property<Guid>("InstructorId")
                                .HasColumnType("uuid");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("InstructorId");

                            b1.ToTable("Instructors");

                            b1.WithOwner()
                                .HasForeignKey("InstructorId");
                        });

                    b.Navigation("Calender")
                        .IsRequired();

                    b.Navigation("InstructorName")
                        .IsRequired();
                });

            modelBuilder.Entity("DrivingSchoolApi.Domain.Entities.Student", b =>
                {
                    b.HasOne("DrivingSchoolApi.Domain.Entities.DrivingSchool", null)
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("DrivingSchoolApi.Domain.Entities.StudentCalender", "Calender", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.ToTable("Students");

                            b1.WithOwner()
                                .HasForeignKey("Id");

                            b1.OwnsMany("DrivingSchoolApi.Domain.ValueObjects.TimeSlot", "TimeSlots", b2 =>
                                {
                                    b2.Property<Guid>("StudentId")
                                        .HasColumnType("uuid");

                                    b2.Property<DateTime>("StartDateTime")
                                        .HasColumnType("timestamp with time zone");

                                    b2.Property<DateTime>("EndDateTime")
                                        .HasColumnType("timestamp with time zone");

                                    b2.Property<string>("Description")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("StudentId", "StartDateTime", "EndDateTime");

                                    b2.ToTable("StudentTimeSlots", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("StudentId");
                                });

                            b1.Navigation("TimeSlots");
                        });

                    b.OwnsOne("DrivingSchoolApi.Domain.ValueObjects.Name", "StudentName", b1 =>
                        {
                            b1.Property<Guid>("StudentId")
                                .HasColumnType("uuid");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("StudentId");

                            b1.ToTable("Students");

                            b1.WithOwner()
                                .HasForeignKey("StudentId");
                        });

                    b.Navigation("Calender")
                        .IsRequired();

                    b.Navigation("StudentName")
                        .IsRequired();
                });

            modelBuilder.Entity("DrivingSchoolApi.Domain.Entities.TheoryLesson", b =>
                {
                    b.HasOne("DrivingSchoolApi.Domain.Entities.Instructor", null)
                        .WithMany()
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DrivingSchoolApi.Domain.Entities.DrivingSchool", null)
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("DrivingSchoolApi.Domain.ValueObjects.Money", "Price", b1 =>
                        {
                            b1.Property<Guid>("TheoryLessonId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("TheoryLessonId");

                            b1.ToTable("TheoryLessons");

                            b1.WithOwner()
                                .HasForeignKey("TheoryLessonId");
                        });

                    b.OwnsMany("DrivingSchoolApi.Domain.Keys.StudentKey", "StudentIds", b1 =>
                        {
                            b1.Property<Guid>("TheoryLessonId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("StudentId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uuid");

                            b1.HasKey("TheoryLessonId", "StudentId");

                            b1.HasIndex("StudentId");

                            b1.ToTable("StudentTheoryLesson", (string)null);

                            b1.HasOne("DrivingSchoolApi.Domain.Entities.Student", null)
                                .WithMany()
                                .HasForeignKey("StudentId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("TheoryLessonId");
                        });

                    b.Navigation("Price")
                        .IsRequired();

                    b.Navigation("StudentIds");
                });
#pragma warning restore 612, 618
        }
    }
}
